azure_region = "West Europe"
azure_rg_name = "vmrsgroup"
linux_flavors = "UbuntuServer"
linux_flavors_sku = "18.04-LTS"
size = "Standard_DS1_v2"
no_vm = 2
type_of_db = "EnableTable"
failover_location = "West US 2"
user_name_databricks_access = "sobhithaa9@gmail.com"
